In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
folder = 'C://Users//karth//OneDrive//Desktop//march-machine-learning-mania-2024//'

Seeds = pd.read_csv(folder + 'MNCAATourneySeeds.csv')
Conferences = pd.read_csv(folder + 'MTeamConferences.csv')

RegularDetail = pd.read_csv(folder + 'MRegularSeasonDetailedResults.csv')
TournetCompact = pd.read_csv(folder + 'MNCAATourneyCompactResults.csv')

display(RegularDetail.columns.values)

array(['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore',
       'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA',
       'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA',
       'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO',
       'LStl', 'LBlk', 'LPF'], dtype=object)

In [14]:
WinTeams = pd.DataFrame()
LoseTeams = pd.DataFrame()

columns = ['Season', 'TeamID', 'Points', 'OppPoints',
       'Loc', 'NumOT', 'FGM', 'FGA', 'FGM3', 'FGA3', 'FTM', 'FTA',
       'OR', 'DR', 'Ast', 'TO', 'Stl', 'Blk', 'PF', 'OppFGM', 'OppFGA',
       'OppFGM3', 'OppFGA3', 'OppFTM', 'OppFTA', 'OppOR', 'OppDR', 'OppAst', 'OppTO',
       'OppStl', 'OppBlk', 'OppPF']

WinTeams[columns] = RegularDetail[['Season', 'WTeamID', 'WScore', 'LScore',
       'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA',
       'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA',
       'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO',
       'LStl', 'LBlk', 'LPF']]

WinTeams['Wins'] = 1
WinTeams['Losses'] = 0

LoseTeams[columns] = RegularDetail[['Season', 'LTeamID', 'LScore', 'WScore',
       'WLoc', 'NumOT', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA',
       'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF', 'WFGM', 'WFGA',
       'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO',
       'WStl', 'WBlk', 'WPF']]

def change_loc(loc):
    if loc == 'H':
        return 'A'
    elif loc == 'A':
        return 'H'
    else:
        return 'N'
    
LoseTeams['Loc'] = LoseTeams['Loc'].apply(change_loc)

LoseTeams['Wins'] = 0
LoseTeams['Losses'] = 1

WinLoseTeams = pd.concat([WinTeams, LoseTeams])
display(WinLoseTeams)

,Season,TeamID,Points,OppPoints,Loc,NumOT,FGM,FGA,FGM3,FGA3,...,OppFTA,OppOR,OppDR,OppAst,OppTO,OppStl,OppBlk,OppPF,Wins,Losses
0,2003,1104,68,62,N,0,27,58,3,14,...,22,10,22,8,18,9,2,20,1,0
1,2003,1272,70,63,N,0,26,62,8,20,...,20,20,25,7,12,8,6,16,1,0
2,2003,1266,73,61,N,0,24,58,8,18,...,23,31,22,9,12,2,5,23,1,0
3,2003,1296,56,50,N,0,18,38,3,9,...,15,17,20,9,19,4,3,23,1,0
4,2003,1400,77,71,N,0,30,61,6,14,...,27,21,15,12,10,7,1,14,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111812,2024,1201,65,67,H,0,23,49,5,21,...,23,8,22,8,12,3,3,15,0,1
111813,2024,1461,76,84,H,0,28,67,9,25,...,21,4,23,11,10,4,8,17,0,1
111814,2024,1156,68,71,H,0,26,70,7,23,...,20,11,31,13,18,3,4,16,0,1
111815,2024,1273,60,73,H,0,22,53,8,19,...,11,6,21,17,6,6,1,13,0,1
111816,2024,1352,77,87,A,0,27,65,10,24,...,28,19,28,15,4,4,1,16,0,1